<?php $_helper = $this->helper('afterpay'); ?>
<tr>
    <td>
        <h2 class="content-heading"><?php echo $_helper->__('AfterPay Module version ');?> <?php echo Mage::getConfig()->getModuleConfig("TIG_Afterpay")->version;?></h2>
        <table id="supportWrap" cellpadding="0" cellspacing="0">
            <tr>
                <td class="col-left">
                    <div class="text-box">
                        <h3><?php echo $_helper->__('First steps');?></h3>
                        <ol>
                            <li><?php echo $_helper->__('Vul de testaccount gegevens in die u van AfterPay ontvangen heeft.');?></li>
                            <li><?php echo $_helper->__('Plaats een of meer testbestellingen om te verifiëren of de bestellingen correct worden verwerkt.');?></li>
                            <li><?php echo $_helper->__('Doorloop de acceptatietest stappen op <a href="http://integration.afterpay.nl">http://integration.afterpay.nl</a> en vraag een acceptatietest aan.');?></li> 
                            <li><?php echo $_helper->__('AfterPay zal vervolgens de implementatie nalopen en indien akkoord de live account gegevens verstrekken');?></li>
                            <li><?php echo $_helper->__('Let op! : AfterPay is niet verantwoordelijk voor bestellingen van consumenten tijdens de testfase! 
                                Wij adviseren u dan ook om duidelijk te vermelden op uw website dat de betaaloptie AfterPay in test is en nog niet beschikbaar. 
                                Dit geldt zolang AfterPay nog geen definitief akkoord voor het live zetten van de AfterPay module heeft gegeven.');?></li> 
                        </ol>
                    </div> 
                    
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Legend');?></h3>
                            <ul id="legend">
                                <li class="disabled"><?php echo $_helper->__('Payment method - Disabled');?></li>
                                <li class="test"><?php echo $_helper->__('Payment method - Test Modus');?></li>
                                <li class="live"><?php echo $_helper->__('Payment method - Live Modus');?></li>
                                <li class="advanced"><?php echo $_helper->__('Advanced Configuration');?></li>
                                <li class="extended"><?php echo $_helper->__('Extended Configuration');?></li>
                            </ul>
                    </div>
                </td>
                
                <td class="col-faux"></td>
        
                <td class="col-right">
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Magento &amp; 3rd party version compatibility');?></h3>
                        <ul>
                            <li><?php echo $_helper->__('Magento Community Edition version');?> 1.6.2.0, 1.7.0.2 &amp; 1.8.1.0</li>
                            <li><?php echo $_helper->__('Magento Enterprise Edition version');?> 1.11.2.0, 1.12.0.2, &amp; 1.13.1.0</li>
                        </ul>
                        <ul>
                            <li><?php echo $_helper->__('OneStepCheckout version');?> 4.0.8</li>
                        </ul>
                    </div>
                    <div class="text-box">
                        <h3><?php echo $_helper->__('Support');?></h3>
                        <p><?php echo $_helper->__('Hulp bij opzetten koppeling?');?></p>
						<p><?php echo $_helper->__('Als u nog niet live bent met de AfterPay betaalmethode en hulp nodig hebt bij het opzetten van de koppeling:');?></p>
                        <table class="contact">
                            <tr>
                                <td class="first"><?php echo $_helper->__('Phone:');?></td>
                                <td class="last">+31(0)513 - 74 41 12 (optie 2)</td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('Mail:');?></td>
                                <td class="last"><a href="mailto:integration@afterpay.nl">integration@afterpay.nl</a></td>
                            </tr>
                        </table>
                        <p><a href="http://www.afterpay.nl" target="_blank"><img src="<?php echo $this->getSkinUrl('images/TIG/Afterpay/'); ?>AfterPay_logo_small.png" alt="" /></a></p>
                        
                        <h4><?php echo $_helper->__('Hulp voor operationele vragen');?></h4>
                        <p><?php echo $_helper->__('Als u al een koppeling heeft en vragen heeft over AfterPay:');?></p>
                        <table class="contact">
                            <tr>
                                <td class="first"><?php echo $_helper->__('Phone:');?></td>
                                <td class="last">+31(0)513 - 74 41 12 (optie 1)</td>
                            </tr>
                            <tr>
                                <td class="first"><?php echo $_helper->__('Mail:');?></td>
                                <td class="last"><a href="mailto:support@afterpay.nl">support@afterpay.nl</a></td>
                            </tr>
                        </table>
                        
                    </div>
                    <div class="text-box">
                        <h3><?php echo $_helper->__('AfterPay integration website');?></h3>
                        <p><?php echo $_helper->__('Zoekt u meer informatie voor het aansluiten van AfterPay op uw webshop. Kijk op de integratie website van AfterPay: <a href="http://www.afterpaydemo.nl">http://www.afterpaydemo.nl</a>.');?></p>
                    </div>
                </td>
            </tr>
        </table>
    </td>
</tr>